# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]["tricky"][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
np.arange(20,35)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [15]:
a = np.arange(0,6).reshape(3,2)
pd.DataFrame(a)

   0  1
0  0  1
1  2  3
2  4  5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
import datetime
from datetime import date
start_date=date(2023,1,1)
end_date=date(2023,2,11)
[date.fromordinal(i) for i in range(start_date.toordinal(),end_date.toordinal())]

[datetime.date(2023, 1, 1),
 datetime.date(2023, 1, 2),
 datetime.date(2023, 1, 3),
 datetime.date(2023, 1, 4),
 datetime.date(2023, 1, 5),
 datetime.date(2023, 1, 6),
 datetime.date(2023, 1, 7),
 datetime.date(2023, 1, 8),
 datetime.date(2023, 1, 9),
 datetime.date(2023, 1, 10),
 datetime.date(2023, 1, 11),
 datetime.date(2023, 1, 12),
 datetime.date(2023, 1, 13),
 datetime.date(2023, 1, 14),
 datetime.date(2023, 1, 15),
 datetime.date(2023, 1, 16),
 datetime.date(2023, 1, 17),
 datetime.date(2023, 1, 18),
 datetime.date(2023, 1, 19),
 datetime.date(2023, 1, 20),
 datetime.date(2023, 1, 21),
 datetime.date(2023, 1, 22),
 datetime.date(2023, 1, 23),
 datetime.date(2023, 1, 24),
 datetime.date(2023, 1, 25),
 datetime.date(2023, 1, 26),
 datetime.date(2023, 1, 27),
 datetime.date(2023, 1, 28),
 datetime.date(2023, 1, 29),
 datetime.date(2023, 1, 30),
 datetime.date(2023, 1, 31),
 datetime.date(2023, 2, 1),
 datetime.date(2023, 2, 2),
 datetime.date(2023, 2, 3),
 datetime.date(2023, 2, 4),
 datetime.date(2023, 2, 5),
 datetime.date(2023, 2, 6),
 datetime.date(2023, 2, 7),
 datetime.date(2023, 2, 8),
 datetime.date(2023, 2, 9),
 datetime.date(2023, 2, 10)]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
pd.DataFrame(lists)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24